name: Process Docker

on:
  push:
    branches:
    # Sequence of patterns matched against refs/tags
    tags:

jobs:

  publish:

    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        with:
          registry: 643vlk6z.gra7.container-registry.ovh.net
          username: ${{ secrets.CS_HARBOR_V2_USERNAME }}
          password: ${{ secrets.CS_HARBOR_V2_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            643vlk6z.gra7.container-registry.ovh.net/world-cereal/ewoc_classif
          # Do not generate :latest tag on Git push tag
          # See https://github.com/marketplace/actions/docker-metadata-action#latest-tag
          flavor: |
            latest=false
          # generate Docker tags based on the following events/attributes
          # See https://github.com/marketplace/actions/docker-metadata-action#tags-input
          tags: |
            type=ref,event=branch
            type=ref,suffix=-{{sha}},event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            EWoC
      # Extract COTS versions from Dockerfile
      - name: COTS Versions
        id: cots-versions
        run: |
          sed -n '/^ARG/s/ARG *\(.*\)=\(.*\)/::set-output name=\1::\2/p' Dockerfile
      - name: Download Classification package
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_classif"
          tag: "${{ steps.cots-versions.outputs.EWOC_CLASSIF_VERSION }}"
          fileName: "ewoc_classif-${{ steps.cots-versions.outputs.EWOC_CLASSIF_VERSION }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Download ewoc_dag
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_dataship"
          tag: "${{ steps.cots-versions.outputs.EWOC_DAG }}"
          fileName: "ewoc_dag-${{ steps.cots-versions.outputs.EWOC_DAG }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Download Classification wrapper package
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/wc-classification"
          tag: "${{ steps.cots-versions.outputs.WORLDCEREAL_CLASSIF_VERSION }}"
          fileName: "worldcereal-${{ steps.cots-versions.outputs.WORLDCEREAL_CLASSIF_VERSION }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Build Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
      - name: Branch name
        id: branch-name
        run: |
          echo ::set-output name=NAME::${GITHUB_REF#refs/heads/}
      - name: Validate
        uses: addnab/docker-run-action@v3
        with:
          image: 643vlk6z.gra7.container-registry.ovh.net/world-cereal/ewoc_classif:${{ steps.branch-name.outputs.NAME }}
          run: /opt/entrypoint.sh python --version && /opt/entrypoint.sh pip show ewoc_classif && /opt/entrypoint.sh pip list && /opt/entrypoint.sh ewoc_classif --help
